modLoader="javafml"
loaderVersion="[4,)"
license="Apache License version 2.0"

[[mods]]
modId="health_tag"
version="2.0.0"
displayName="Health Tag"
displayURL="https://github.com/Dreyka-Oas/HealthTag.git"
logoFile="logo.png"
credits="O.A.S"
authors="Dreyka Oas"
description="Displays entity health as nametags"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.health_tag]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.101-beta,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.health_tag]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration